version: "3.7"

services:
  ergogen:
    user: $USERID:$GROUPID
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./footprints
        target: /app/src/footprints
      - type: bind
        source: ./config.yaml
        target: /app/src/config.yaml
      - type: bind
        source: ./build
        target: /app/build