version: "3.7"

services:
  ergogen:
    user: $USERID:$GROUPID
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./project
        target: /app/project
      - type: bind
        source: ./build
        target: /app/build